### ISSUE TITLE
Installation without docker

### ISSUE THREAD

**Issue by s0kil** [dairycart/dairycart#76]
Is there a way to install without docker?

**Comment by verygoodsoftwarenotvirus** [comment]
Hi @DanielSokil,

Currently Dairycart is not stable software, and is subject to radical change without any responsibility of notice or update. It is not designed for production use and has been vetted by only its author for code quality and security concerns. It is my solemn advice, as the author of this entire project, that you choose other software for your eCommerce needs until otherwise stated by myself specifically in the README.

That warned, hypothetically, I think you could run something like:

```bash
go get github.com/dairycart/dairycart
go build -o dairycart github.com/dairycart/dairycart/cmd/server/v1
```

to get a binary of the API server. You can extrapolate from there to figure out how to run the API server. Using the supplied docker-compose files is the best way I can tell you to run the project at the moment.

Thank you so much for your interest in Dairycart. :)
